### ISSUE TITLE
Provide copy in German for GDR campaign

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/petitions.mozilla.org#10]
@shaghdoosti let's track the progress of copy here. @alicoding can integrate as soon as it's ready.

- [x] petition copy drafted
- [x] petition copy translated
- [x] petition copy installed (on staging server)
- [x] petition copy reviewed (on staging server)
- [x] thank you page copy drafted
- [x] thank you page copy translated
- [x] thank you page copy installed (on staging server)
- [x] thank you page copy reviewed (on staging server)

**Comment by shaghdoosti** [comment]
Hey everyone,

Here is the list of things that need to be translated - please have a look and add in anything as I'm sending everything to the translator today. 

https://docs.google.com/document/d/1wz-lTUYcy1EdD60hGE3NaJ-LktiRNdqPzCfvV_zKQtA/edit

**Comment by shaghdoosti** [comment]
Here is the timeline for translation: 

Wednesday COB - Text sent to translation contractor 
Thursday Morning - We receive text from the Contractor. I imagine this text will be 90% what we use so if you want to do initial staging (knowing there will be minor changes) that's great. 
Thursday Morning - Translation sent to Sebastian from German L10N community for Comments.
Friday Afternoon - We have Sebastian's Comments. 
Friday Afternoon - Send to Alex K for final sign off. 
Monday Afternoon - We have final text.

**Comment by secretrobotron** [comment]
@adamlofting @ScottDowne @alicoding anything we're missing from the doc above that needs to be translated? (Even form fields)

@alicoding since we'll have a draft on Thursday morning, can we put some of the text in to start getting some review done? We might just run into some trouble with long titles or something again — stuff that we can get out ahead of.

**Comment by shaghdoosti** [comment]
Campaign text has been approved by Policy and Comms. I just sent everything to the translator. 

Here is the link to the English text. (Please note it is locked) https://docs.google.com/document/d/1dI5eQlfjR1uYhWF0_tmtbEqM1aDm1wt2VEwHTeR84rM/edit

**Comment by alicoding** [comment]
@shaghdoosti the document doesn't seem to be locked for me even when I'm sign out.

**Comment by shaghdoosti** [comment]
Hey everyone - 

Here is the German text from the contractor - This still has to be reviewed by Sebastian and Alex so there will probably be a few tweeks but I imagine 90% of this will stay the same. 

https://docs.google.com/document/d/1i1tyqkAY1xWmE4XlyDuE2QxNjcx1hvP-814gW3nUkZk/edit

**Comment by shaghdoosti** [comment]
Quick update. Sebastian got back to us with his comments about the translation. I've sent that document to Alex and am hoping we'll get the final copy locked down tomorrow morning. (No promises - it could very well still take till Monday)

**Comment by shaghdoosti** [comment]
Hey Everyone - 

Here is the final German Copy: 

https://docs.google.com/document/d/1i1tyqkAY1xWmE4XlyDuE2QxNjcx1hvP-814gW3nUkZk/edit
