### ISSUE TITLE
Facebook unable to scrape pages

### ISSUE THREAD

**Issue by jpetto** [mozilla/petitions.mozilla.org#113]
While testing the Facebook share button on the newly pushed [`/stay-secure/thank-you/`](https://petitions.mozilla.org/stay-secure/thank-you/) page, noticed that no Open Graph information is being shown/populated on the resulting Facebook share page.

Tried to debug the URL using [Facebook's Open Graph object debugger](https://developers.facebook.com/tools/debug/og/object/), which returns no open graph information about the page at all. The ["See exactly what our scraper sees for your URL" link](https://developers.facebook.com/tools/debug/og/echo?q=https%3A%2F%2Fpetitions.mozilla.org%2Fstay-secure%2F) results in a blank page. Tested `https://petitions.mozilla.org/data-retention/` as well with the same results. :disappointed: 

Sharing is an important part of the Data Privacy Day campaign launching today.

@jbuck @ScottDowne - Any ideas here?

**Comment by jbuck** [comment]
@alicoding did we ever figure this out?

**Comment by jbuck** [comment]
@jpetto is it as simple as there is no opengraph data on that page?

**Comment by alicoding** [comment]
@jbuck no, but for our staging is still seem to be broken and our prod for donate.mozilla.org works perfectly. I think this is something has to do with CDN or something I'm not sure.

**Comment by jpetto** [comment]
There is definitely open graph data on the pages. I put a [static version of the page](http://petitions.equalparts.io/stay-secure/) up yesterday for testing, which Facebook's debugger scrapes successfully.

**Comment by jbuck** [comment]
I'm going to run an invalidation on the CDN just to be sure it didn't cache anything it shouldn't have...

**Comment by jbuck** [comment]
Man, I have no frigging clue why it's doing this.

**Comment by jpetto** [comment]
One curious piece of data from the Facebook debugger is that the response code (for both `/data-retention/` and `/stay-secure/`) is 206 (partial content).

**Comment by jpetto** [comment]
Doing a little more digging, I see the following header included when running `curl -I https://petitions.mozilla.org/stay-secure/`:

```
Accept-Ranges: bytes
```

Based on a whole 10 minutes of research, this header and a 206 response code go hand-in-hand. Also, it seems this header is generally used for streaming large content (e.g. videos). Is there a specific reason to include this header? Would it be difficult to (possibly temporarily) turn it off?

**Comment by jpetto** [comment]
Final observation before lunch - donate.mozilla.org (which @alicoding says is fine in this regard) does not appear to have the `Accept-Ranges` header set.

**Comment by jbuck** [comment]
@jpetto fascinating! Okay, I'll see if I can figure out why that is.

**Comment by jpetto** [comment]
@jgmize found a [related bug](https://bugzilla.mozilla.org/show_bug.cgi?id=725253#c2). Might be of some help, but I still would like to see what happens when that `Accept-Ranges` header is removed.

**Comment by jpetto** [comment]
Just checking in - any update?

**Comment by jbuck** [comment]
@jpetto um, I don't know why, but it appears to be working better now: https://developers.facebook.com/tools/debug/og/object/?q=https%3A%2F%2Fpetitions.mozilla.org%2Fstay-secure%2F

Should we add the FB share button back?

**Comment by jpetto** [comment]
Well, that certainly is curious. :confused: I'd love to know *why* it's suddenly working...

Anyway, yeah, I'll make a PR to re-add the FB button.

**Comment by jpetto** [comment]
@jbuck Should we leave this issue open until we know why things weren't working and then suddenly were? Or just chalk it up to Facebook being a black box and close? Your call.

**Comment by jbuck** [comment]
Facebook is a black box alright :/

**Comment by jbuck** [comment]
There's a fix in Hapi 13 for this now: https://github.com/hapijs/hapi/commit/0c8109e1b573528bfebea771da6a83d1f5bf7043
