### ISSUE TITLE
Decide on a URL for GDR campaign

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/petitions.mozilla.org#12]
Any preference for url, @shaghdoosti?

Something like...
- petitions.mozilla.org/germany
- petitions.mozilla.org/data-retention
- petitions.mozilla.org/vorratsdatenspeicherung
- petitions.mozilla.org/daten
- petitions.mozilla.org/datenfreiheit

**Comment by shaghdoosti** [comment]
I like this one the best: 

petitions.mozilla.org/data-retention

**Comment by secretrobotron** [comment]
@shaghdoosti cool. That's not an exhaustive list of possibilities. Feel free to get creative :P. Otherwise, we'll just go with that.

@jbuck, once @shaghdoosti confirms, can we point at that url?

**Comment by jbuck** [comment]
Yeah, whoever is working on actually landing the template in the repo just needs to name their file appropriately.

**Comment by secretrobotron** [comment]
@ScottDowne can you make sure this happens?

**Comment by ScottDowne** [comment]
Updated it to be /data-retention now.

On prod it should end up as petitions.mozilla.org/data-retention/
