### ISSUE TITLE
Remove Mozilla tabzilla

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/petitions.mozilla.org#14]
Previously, @lovegushwa mentioned we should remove tabzilla. That still sound sensible?

**Comment by ScottDowne** [comment]
I say remove it.

**Comment by lovegushwa** [comment]
yes, lets.  ... This is old, but it should get the idea across. @ScottDowne let me know if you want to sit and push CSS around if needed.
<img width="1465" alt="germany" src="https://cloud.githubusercontent.com/assets/12228435/9890066/939c0f58-5bb2-11e5-9866-48795a427c0b.png">

**Comment by secretrobotron** [comment]
Awesome.

**Comment by ScottDowne** [comment]
Landed: https://github.com/mozilla/petitions.mozilla.org/commit/e8b80bdc3d02175086d553e298f724c8eb600b43
