### ISSUE TITLE
Email double opt-in list setup

### ISSUE THREAD

**Issue by adamlofting** [mozilla/petitions.mozilla.org#2]
The list for DE will be setup in Exact Target. Exact Target has double opt-in functionality built in. MoCo uses this for managing their DE mailing lists.

We will subscribe people to the list using the Basket API: http://basket.readthedocs.org/en/latest/newsletter_api.html#news-subscribe

@adamlofting to work on the list setup in ET
Then pass list details to @ScottDowne and @alicoding for use with the sign-up form.

cc/ @valianttry @edrushka @secretrobotron @shaghdoosti

**Comment by adamlofting** [comment]
Just noting related bug for language lives here: https://bugzilla.mozilla.org/show_bug.cgi?id=1202841

**Comment by jbuck** [comment]
@adamlofting after you're done the list setup, I'll do the implementation on petitions.m.o

**Comment by adamlofting** [comment]
Sign-up list is implemented on Basket Staging, unblocking #9 

There are still open tasks to setup the opt-in email. I'll file that as a separate bug.

**Comment by secretrobotron** [comment]
Hey @adamlofting, what's the status on this? The rest of the setup was finished and tested today. This part is the final piece of the puzzle.

**Comment by adamlofting** [comment]
I'll follow up in this today.

**Comment by adamlofting** [comment]
Adding @jessilyndavis to the thread.

Basket Dev now has 'placeholder' confirmation emails live. These are functional, but do not include the copy / design.

@jessilyndavis is working on the Staging and Production versions of these today so we can finish the rest of QA soon.

**Comment by secretrobotron** [comment]
Excellent! Thanks @jessilyndavis & @adamlofting. Let us know when we can start testing again.

Any sense of when that will be?

**Comment by jessilyndavis** [comment]
Basket, and the double opt-in & welcome emails for EN and DE languages (with placeholder copy), has been configured for Dev (not stage): https://basket-dev.allizom.org

Working on setting up Stage and Prod instances of ExactTarget and Basket today. Will confirm when it's ready.

**Comment by alicoding** [comment]
![](https://dl.dropboxusercontent.com/spa/n5v3bx9nnjkdpzf/q28t2vp0.png)
![](https://dl.dropboxusercontent.com/spa/n5v3bx9nnjkdpzf/huhnf33j.png)
![](https://dl.dropboxusercontent.com/spa/n5v3bx9nnjkdpzf/hcrhr3_l.png)

**Comment by secretrobotron** [comment]
Thanks @jessilyndavis. @alicoding tooks some screens of progress using the dev env ^^.

**Comment by jessilyndavis** [comment]
Thanks @secretrobotron and @alicoding . The double opt-in seems to have been triggered, but the welcome fired in EN (not DE like the confirm email and URL landing page). 

Your email preferences are DE and HTML: 
https://www-dev.allizom.org/en-US/newsletter/existing/09cbaba8-7941-468b-ba16-6b78bcfdadca/

I'm investigating now.

**Comment by jessilyndavis** [comment]
Updated basket to accomodate "de" as an accepted language.

@alicoding  - can you try the German language signup with a new unique email address again?

**Comment by alicoding** [comment]
@jessilyndavis just tried to signup again.

**Comment by shaghdoosti** [comment]
Hey @jessilyndavis @adamlofting 

I asked Alex from our Berlin team to give it a test as well. He's what he found:

He received the optin email and the confirmation email after clicking the optin. 
The optin email went to his spam. 
Below is the text he received - so the copy isn't right yet. 

+++++First email+++++

Mozilla Foundation - "HTML" & DE email on dev + ET sandbox account combo 

GERMAN!

************************************
Hello!

Please confirm your interest in receiving our newsletter by clicking here:

http://cl.test.exacttarget.com/?qs=5f727b690564e418e50a92f91a9ba0978afd0faeeed6fe9baba2be0d179a57e7 



Until you confirm, you will not be added to our email list. 


Thanks!
The Mozilla Team

************************************
Mozilla
650 Castro St., Ste 300
Mountain View, CA 94041-2021


Read the Mozilla Privacy Policy:
http://cl.test.exacttarget.com/?qs=5f727b690564e418ca50238708ff67b412319b5b9ed6f1bc39533a7cc3cd93cb


++++++Second email++++

Mozilla Foundation

"HTML" & DE email on dev + ET sandbox account combo 



******************************************
Welcome!
******************************************

We're excited to connect with you! Thanks for being part of our community. 



******************************************
Thanks for reading!
******************************************
You're receiving this email because you subscribed to receive email newsletters and information from Mozilla. If you do not wish to receive these newsletters, please click the Unsubscribe link below.


Unsubscribe
http://cl.test.exacttarget.com/?qs=fd9c572de20b4a023f75cd8ceabe499840027bdb7204177304f7454f54882f4b 


Modify your preferences
http://cl.test.exacttarget.com/?qs=fd9c572de20b4a023f75cd8ceabe499840027bdb7204177304f7454f54882f4b 


******************************************
Mozilla
650 Castro St., Ste 300
Mountain View CA 94041-2021


Mozilla Privacy Policy
http://cl.test.exacttarget.com/?qs=fd9c572de20b4a029e56c69e1dde25ff10d3c114b0ded8c220b33c1457485b15

**Comment by jessilyndavis** [comment]
Thanks @shaghdoosti !  The test is actually okay given that both the optin confirm email, and the welcome email, were both sent with the placeholder text of ""HTML" & DE". That was the part we wanted to make sure worked for this test.

I'm working on setting up the real language and templates in Production ET account which will be hooked into Basket Stage and Basket Prod. Basket Dev will still point to this placeholder text.

I'll update you as soon as it's ready for testing in Basket Stage.

Thanks!

**Comment by jessilyndavis** [comment]
Hello!

Basket Stage and Prod are updated, as is production ExactTarget with the confirm emails for the main "Mozilla Foundation" newsletter in both EN and DE.

Please test stage thoroughly before deploying to Prod. To make sure you check that the double opt-in confirm link is working on *stage*, please sign up for the newsletter using Text format, and change the link from mozilla.org/newsletter/confirm/TOKEN - to allizom.mozilla.org/newsletter/... (Stage and Prod versions of Basket use Production ET - so the links from the confirm email point to Production by default.)

Keep me posted on how testing goes, and if you have any questions.

I'm going to take a stab at updating the Mozilla template for the German version. (So the footer isn't in English).

**Comment by jessilyndavis** [comment]
DE and EN templates have been updated to remove the unsubscribe blurb and link (since this is a transactional email, and if they don't confirm, they are not subscribed). DE's HTML emails now say the correct information in German.

**Comment by jessilyndavis** [comment]
FYI - the emails should be coming from "Mozilla <mozilla@e.mozilla.org>" and the reply to email address is "joinmozilla@mozilla.org". Please make sure and verify this information.

Also, HTML emails will have tracking enabled. Text only emails will not, so you should see in Text the mozilla.org/newsletter/confirm/TOKEN link (not a tracking link).

I'd love to see this before it goes live just to give it a once over and make sure all is well.

Thanks!

**Comment by jessilyndavis** [comment]
Also - if there's a welcome email we can set up (in EN or DE) to be sent when someone confirms, that will be the easiest way to make sure the double opt-in process is working (and gives a better user experience). (Otherwise we have to do some query work in ET - not a blocker, but requires me to be on hand at the moment until Adam and/or someone on Foundation team is trained to look.)

**Comment by secretrobotron** [comment]
@jessilyndavis 
* from: Mozilla@e.mozilla.org
* reply-to: Mozilla Foundation <reply-xxxxxxxxxxxxxxxxxxxxxx-xxx_HTML-xxxxxxxxxx-xxxxxxxxx-x@e.mozilla.org>

**Comment by secretrobotron** [comment]
@jessilyndavis I don't think we have a confirmation welcome email (specific to this campaign, @shaghdoosti correct me if I'm wrong). Could you explain a bit more why that's better to have?

**Comment by jessilyndavis** [comment]
@secretrobotron - can you send a test reply to that gobbldy-gook email and make sure it goes through to joinmozilla@mozilla.org ? (I'm not sure who owns that email address - @shaghdoosti ?)

It's better to have a welcome for 2 reasons: 
1) if you get a welcome email, we know the confirm process worked without having to go digging through the databases
2) if someone opts in & confirms, then they are actively engaged with you in their email inbox. It's prime time to send them a personal welcome message about what they've just signed up for, a sample piece of content, and even another ask for them to do something else to get more involved.  It's not a make it or break it thing - it's just a good email marketing/engagement practice.

**Comment by adamlofting** [comment]
Just noting that the Welcome email is something we should look at in the future as part of overall MoFo email programme. But right now we don't have an existing email, and we don't have time to write this and translate it into DE for this immediate campaign.

**Comment by jessilyndavis** [comment]
Sounds like a plan.

Can someone retest the confirm email and make sure it doesn't have the added header (To view this email...) + footer (this email was sent to....) like it shows in: https://www.dropbox.com/s/xpekclyto0se551/Screenshot%202015-09-24%2012.03.35.png?dl=0

**Comment by shaghdoosti** [comment]
Hey - 

A few things @jessilyndavis in the emails that Ben sent me there was one asking for users to optin and a second one telling them that it had been confirmed. Is the second email not what your referring to? 

@adamlofting 100% agree - I don't think that we have time to translate a welcome email now - but I think it should be something we do in the future and with this campaign I'm planning on sending people a survey in the next two weeks. 

@secretrobotron Yes - I get joinmozilla@ emails.

**Comment by secretrobotron** [comment]
@jessilyndavis: replied to the email I got. @shaghdoosti can you see if you get a "LOL TEST!" message to joinmozilla?

**Comment by shaghdoosti** [comment]
Yep - got it.

**Comment by secretrobotron** [comment]
@jessilyndavis: https://www.dropbox.com/s/huxr277s0ss1699/Screenshot%202015-09-24%2013.04.03.png?dl=0

<img width="661" alt="screenshot 2015-09-24 13 04 03" src="https://cloud.githubusercontent.com/assets/403231/10080279/ce7af628-62bc-11e5-87b1-fed9b67ebf78.png">

**Comment by jessilyndavis** [comment]
Thanks @secretrobotron  - thats' a bug and blocker. Calling ET now. :/

**Comment by secretrobotron** [comment]
Thanks, @jessilyndavis ~~~~ʕ ´ᴥ`ʔ~~~~~~~~~

**Comment by jessilyndavis** [comment]
I just tried a fix on the DE - HTML version. Can you retry?

**Comment by shaghdoosti** [comment]
Yep I'll retry.

**Comment by jessilyndavis** [comment]
Thanks! Make sure you test with a unique email address.

**Comment by shaghdoosti** [comment]
Here's what I got: 

![screen shot 2015-09-24 at 10 56 08 am](https://cloud.githubusercontent.com/assets/13626384/10081686/f992cbae-62aa-11e5-8f61-a74591b53f6f.png)

![screen shot 2015-09-24 at 10 56 19 am](https://cloud.githubusercontent.com/assets/13626384/10081693/00c1f2f6-62ab-11e5-8e2e-09f0e8282962.png)

**Comment by jessilyndavis** [comment]
Is there a "view email in browser" link at the top or "this email was sent to" at the bottom?

**Comment by shaghdoosti** [comment]
The top - is the email I was sent. 

The second image is the message once I clicked on the link.

**Comment by jessilyndavis** [comment]
Right - but it looks like the top & bottom of the email message screenshot are cut off. Does it look different than: https://www.dropbox.com/s/huxr277s0ss1699/Screenshot%202015-09-24%2013.04.03.png?dl=0

**Comment by shaghdoosti** [comment]
Here it is: 

![screen shot 2015-09-24 at 11 00 20 am](https://cloud.githubusercontent.com/assets/13626384/10081784/7a26c342-62ab-11e5-8033-a8ac2e3ab237.png)

**Comment by jessilyndavis** [comment]
Perfect! If ET doesn't fix it the proper way in the next few minutes, I'll apply this workaround to the EN - HTML, Text, and DE - Text versions.

Looking up the confirm process for the test emails now to make sure the confirm link is working properly.

**Comment by shaghdoosti** [comment]
Great!

**Comment by jessilyndavis** [comment]
Okay - updated EN - HTML. Can you give it a try?

And I just spot checked one of the tokens to make sure it showed up as confirmed in our system - and it did. :) So all seems to be working there! \o/

**Comment by shaghdoosti** [comment]
Yep - 

Here's what I got: 

![screen shot 2015-09-24 at 11 23 10 am](https://cloud.githubusercontent.com/assets/13626384/10082460/b2ca4072-62ae-11e5-8019-ddd2a4399f16.png)

**Comment by jessilyndavis** [comment]
Thanks Sara! That's the German version though. Can you try the English version? (Or did the English form send the German email?)

**Comment by shaghdoosti** [comment]
Sorry - this might be silly but where do I get the english version? I tested it through the petition page which is only in German.

**Comment by jessilyndavis** [comment]
That's a question for @secretrobotron ?  It's possible that this is only in German.
(I set up EN too so that it's ready for migrating other Foundation newsletter forms and if you'd like to have an English version of the Germany campaign.)

**Comment by alicoding** [comment]
Our petition was only setup to work in German, so I don't think you can test from the site

**Comment by jessilyndavis** [comment]
Ah cool. Alright! All that's needed then is testing the Production campaign to make sure basket Prod is working well, and then it's good to go.

**Comment by alicoding** [comment]
Just tested on production and got the email :)

**Comment by secretrobotron** [comment]
Me too.

**Comment by jessilyndavis** [comment]
Tested and talked in #petitions. Email double opt-in process worked, confirm query update worked, email preference center unsubscribe process worked (record was updated in Double_Opt_In, then in Master_Subscribers after opt-in was confirmed). Description for "Mozilla Foundation" is still in EN, Jess (me) to file bug to get this localized.

This is good to launch from email POV.

**Comment by secretrobotron** [comment]
Thanks @jessilyndavis !

Make rocket go now! :rocket:
