### ISSUE TITLE
Copy required for double opt-in confirmation email

### ISSUE THREAD

**Issue by adamlofting** [mozilla/petitions.mozilla.org#21]
@valianttry we need to decide on copy for the double opt-in confirmation email.

Options are:
1. Use the existing copy from MoCos newsletter (DE translation already exists)
2. Write something new, and get it translated (time constraints...)

This copy is generic to the MoFo list (not specific to this campaign) so it makes sense to keep it simple.

##### Existing MoCo confirmation email example

Below is the existing text in the Firefox and You newsletter. We'd just need to replace the title `Firefox + You` with `Mozilla Foundation` in the body copy.

**Note: We'll be using our existing MoFo email template - this bug is just about the copy in the email**

<img width="494" alt="screenshot 2015-09-15 16 10 11" src="https://cloud.githubusercontent.com/assets/1901816/9908142/3739c47a-5c8a-11e5-9c08-e0461c3a3292.png">

**Comment by secretrobotron** [comment]
Linking to https://github.com/mozilla/petitions.mozilla.org/issues/10

**Comment by valianttry** [comment]
@shaghdoosti just got this information from legal and from Ben Niolet. She can confirm here (I'm in TRIBE ATM)

**Comment by shaghdoosti** [comment]
Hey legal just confirmed we can use this language for the optin email. We just need to change the words 'firefox' to 'Mozilla campaigns'

The copy in both German and English are below: 

++++++

Subject: 

 Jetzt sind Sie dran: Bestätigen Sie Ihr Abonnement von "Firefox & Du"!


Body Text: 

Firefox & Du

******************************************
Bitte bestätigen Sie Ihr Abonnement 
******************************************

Hallo! Nur noch einen Schritt, dann ist es geschafft. Sobald Sie Ihr Abonnement bestätigt haben, erhalten Sie unseren "Firefox & Du"-Newsletter. 


Bestätigen Sie Ihr Abonnement >>

https://www.mozilla.org/de-DE/newsletter/confirm/%%token%%/ 


****************************************** 
Mozilla
331 E. Evelyn Avenue
Mountain View CA 94041


Lesen Sie die Datenschutzgrundsätze von Mozilla .
https://www.mozilla.org/privacy-policy.html 



______________________________________________________________

English:

Subject: Action required: Confirm your subscription to Firefox + You

Body: 

Firefox + You

******************************************
Please confirm your subscription 
******************************************

Hello! Just one more step, and you’ll be set. Once you confirm, you’ll start receiving our Firefox + You email newsletter. 


CONFIRM YOUR SUBSCRIPTION >>

https://www.mozilla.org/en-US/newsletter/confirm/%%token%%/ 


****************************************** 
Mozilla
331 E. Evelyn Avenue
Mountain View CA 94041

Read the Mozilla Privacy Policy .
https://www.mozilla.org/privacy-policy.html
