### ISSUE TITLE
Icon for snippet

### ISSUE THREAD

**Issue by shaghdoosti** [mozilla/petitions.mozilla.org#23]
@secretrobotron @adamlofting @ScottDowne 

I just talked to Chelsea and she said that their team are expecting a snippet icon from us. I don't think this needs to be complicated (a lock for example would be perfect). Let me know what the best way to move this forward is.

**Comment by ScottDowne** [comment]
@lovegushwa thoughts?

**Comment by lovegushwa** [comment]
@ScottDowne the lock is perfect. @edrushka do you know where I can find the lock .png by chance?

**Comment by edrushka** [comment]
Why yes! It's here: https://bug1076019.bmoattachments.org/attachment.cgi?id=8500707

**Comment by edrushka** [comment]
Actually that's a gif. @sabrinang might know where to find the png.

**Comment by sabrinang** [comment]
@edrushka :open_mouth: I was looking all over for that lock .gif earlier when @lovegushwa was asking me about it. I totally forgot about bugzilla.

Unfortunately, I don't know where are the .png or .gif for the old lock, heart or coin graphics done for 2013 are.

**Comment by edrushka** [comment]
@sabrinang there's a ton of stuff here in this bug, but not the static lock or the lock png

https://bugzilla.mozilla.org/show_bug.cgi?id=1076019

**Comment by ScottDowne** [comment]
I wonder if what we need is hiding in bsd assets? I'll take a look tomorrow.

**Comment by valianttry** [comment]
the lock was designed by MoCo. I think i found the files. 

![locksnippet_40x50px](https://cloud.githubusercontent.com/assets/9830371/9924875/c9bd0f04-5cb8-11e5-90bd-be2ce0ad58f6.gif)

**Comment by secretrobotron** [comment]
Ok! Looks like we've got what we need. Good to pass on to @chelseanovak, @valianttry @shaghdoosti?
