### ISSUE TITLE
Create a share page

### ISSUE THREAD

**Issue by ScottDowne** [mozilla/petitions.mozilla.org#24]
I'm thinking we recycle this: https://donate.mofostaging.net/de/share/

English is here so we can see what it says: https://donate.mofostaging.net/en-US/share/

That is if we still want a share page.

**Comment by shaghdoosti** [comment]
That looks great.

**Comment by ScottDowne** [comment]
Share and thank you are now the same page: https://github.com/mozilla/petitions.mozilla.org/commit/29b6f5e9aab1cd1703eead96dbccd77e3f0d8647

**Comment by lovegushwa** [comment]
@alicoding @ScottDowne 

This is a screenshot of the current form:

<img width="1724" alt="screen shot 2015-09-17 at 2 25 36 pm" src="https://cloud.githubusercontent.com/assets/12228435/9949096/96d9849a-5d5e-11e5-8723-0c1be842adc7.png">

I made a few tweaks here:
<img width="1058" alt="screen shot 2015-09-17 at 5 19 40 pm" src="https://cloud.githubusercontent.com/assets/12228435/9949358/77908988-5d60-11e5-873c-ba37a7e13604.png">

An overlay of the old and new version should show you:
-  I changed the paragraph alignment to centered and moved it a bit higher, 
- centered the Mozilla logo and made it smaller. ~110 px, you can match the logo in the footer.
- Moved the facebook and twitter icons about 10px lower so they are now visually centered in the share block:
<img width="1048" alt="screen shot 2015-09-17 at 5 20 00 pm" src="https://cloud.githubusercontent.com/assets/12228435/9949394/f0ea5b74-5d60-11e5-86b0-48a343993236.png">

**Comment by alicoding** [comment]
This is done I think.
