### ISSUE TITLE
Decide on error messages and get them translated

### ISSUE THREAD

**Issue by ScottDowne** [mozilla/petitions.mozilla.org#29]
The error messages I chose are placeholders. Please don't rely on me for copy like this :P

We need to decide on error messages for these states, then translate them.

![petition1](https://cloud.githubusercontent.com/assets/197334/9939049/40873934-5d36-11e5-819b-b889037a20a7.png)

cc @shaghdoosti 

The states are:
1. first and last names are required. currently: Oops, please complete fields highlighted in red.
2. country is required. currently: Country is required.
3. email is invalid. currently: Your email address is invalid.
4. privacy checkbox is required. currently: To submit this form you must agree with our privacy policy.

**Comment by secretrobotron** [comment]
(See #20.)

**Comment by secretrobotron** [comment]
1. Please complete fields highlighted in red.
2. Please choose a country. (could just be the same as the first one though)
3. Please make sure you have entered a valid email address.
4. You must agree with our privacy policy.

**Comment by shaghdoosti** [comment]
Okay - I'll write this up and send it to the translator now. We should get it back by tomorrow.

**Comment by shaghdoosti** [comment]
@valianttry @alicoding @secretrobotron 

Andrea mentioned that these things were already translated for the donation form? Do others have access to that translation?

**Comment by shaghdoosti** [comment]
@alicoding 

This is what I had sent to the translator - can you confirm that these phrases have already been translated in which case I will cancel the translation.

https://docs.google.com/document/d/1hzlg4iVXzdkyfOAeWsRMuuXxUxBa3PXMSRCYfFcKNaw/edit

**Comment by alicoding** [comment]
@shaghdoosti We actually don't have them on donation form. I just checked, so we should just send them to get translate anyway.

**Comment by shaghdoosti** [comment]
Okay great.

**Comment by shaghdoosti** [comment]
Hey @ScottDowne, @alicoding 

Here is the translated text: 

https://docs.google.com/document/d/1-pcCPTidnxNhXU-5PN7dcrqzpZBQvSvxG3XXJCQ1ap4/edit

Here it is in English: 

https://docs.google.com/document/d/1hzlg4iVXzdkyfOAeWsRMuuXxUxBa3PXMSRCYfFcKNaw/edit

**Comment by ScottDowne** [comment]
This landed.
