### ISSUE TITLE
Where will petition data be stored?

### ISSUE THREAD

**Issue by jbuck** [mozilla/petitions.mozilla.org#30]
We're going to use ET to store email sign-ups, but it doesn't let us do something like store their first and last name. Where do we store that information?

**Comment by shaghdoosti** [comment]
@valianttry @secretrobotron - I don't know the answer to this - any thoughts?

**Comment by secretrobotron** [comment]
Just talked to @ScottDowne. It's connected to BSD at the moment, just as it has been in the past.

@adamlofting, should we try to use ET exclusively (if there's a way)?

**Comment by ScottDowne** [comment]
I confirmed, it still works.

**Comment by jbuck** [comment]
Okay, BSD it is!

**Comment by adamlofting** [comment]
Just confirming - the recorded petition data should live in BSD for now (recording this action must not subscribe the user in to any email lists in BSD).

**Comment by ScottDowne** [comment]
@adamlofting exactly
