### ISSUE TITLE
Formatting petition page 

### ISSUE THREAD

**Issue by shaghdoosti** [mozilla/petitions.mozilla.org#35]
@alicoding @secretrobotron 

It's very exciting to see this campaign come together. I've seen the mockup here: 

http://ali.ngrok.io/data-retention/

I have a few questions: 

-Can the petition text be below the introduction?
-Can it be in italic? Ie: 

++++

You should sign this petition because it's super important. 

Below is the petition text: 

<i>Dear target - please stop data retention. </i>

**Comment by alicoding** [comment]
@shaghdoosti I updated the text to make it italic, but not sure which one to move?

**Comment by shaghdoosti** [comment]
Petition text - should be under petition intro: 

They're labeled in here: 

https://docs.google.com/document/d/1i1tyqkAY1xWmE4XlyDuE2QxNjcx1hvP-814gW3nUkZk/edit
