### ISSUE TITLE
Clear or remake the petition data

### ISSUE THREAD

**Issue by ScottDowne** [mozilla/petitions.mozilla.org#37]
At the moment, we're storing the petition data under a test petition page in BSD.

Either before we launch, we update that or clear it (it's full of nonsense I put in there)

Or, we configure the endpointt be different between staging, prod, and local

**Comment by secretrobotron** [comment]
@ScottDowne's going to just change the name/slug of the current BSD form. Easy to change in config on our side.

**Comment by ScottDowne** [comment]
Updated the url to go to https://sendto.mozilla.org/page/s/data-retention

This is going to need to be updated i @jbuck s patch.

The old endpoint is dead.

The page itself has has it's content removed, so going to the link you shouldn't see much, but that updated might take BSD some times to display it live.

**Comment by ScottDowne** [comment]
Let's keep this open for now and I'll close once the blockers have landed.

**Comment by jbuck** [comment]
@ScottDowne I fixed it in https://github.com/mozilla/petitions.mozilla.org/blob/69addf8e20f2573215b3659618d1416b19b2748c/lib/campaigns.js#L3
