### ISSUE TITLE
Create social share graphic(s) for German advocacy campaign

### ISSUE THREAD

**Issue by edrushka** [mozilla/petitions.mozilla.org#4]
Create one or more share graphics specifically for the German advocacy campaign. These will be for donors to share on their own channels, not for Moz to use on its official Twitter and FB.

Themes for these shares could include: user control and Mozilla is non-corporate. Careful not to make the imagery look related to the current refugee crisis.

This is a nice-to-have for the advocacy campaign, not a P1.

cc @valianttry @secretrobotron @shaghdoosti

**Comment by ScottDowne** [comment]
@edrushka To confirm, this isn't something that is displayed in a share page? We're still not having a share page, right?

**Comment by edrushka** [comment]
I believe we *are* having a share page (as a P2). @shaghdoosti please confirm.

**Comment by shaghdoosti** [comment]
Hey @edrushka - Yes, we would love to have a share page (as a P2).

Thanks!

**Comment by edrushka** [comment]
@ScottDowne is this possible?

**Comment by ScottDowne** [comment]
@edrushka yeah, possible. Do we know what the share page would look like?

**Comment by lovegushwa** [comment]
@ScottDowne @edrushka 
Scott and I discussed this, I believe he is going to find an old form (maybe from fundraising?) and recycle and I'll check in on its looks.

**Comment by ScottDowne** [comment]
@lovegushwa I filed a specific build ticket with the examples as well: https://github.com/mozilla/petitions.mozilla.org/issues/24

**Comment by secretrobotron** [comment]
@lovegushwa any progress here?

**Comment by lovegushwa** [comment]
@secretrobotron we are not creating a graphic (this is a text only share.)
