### ISSUE TITLE
Create a thank you page

### ISSUE THREAD

**Issue by ScottDowne** [mozilla/petitions.mozilla.org#5]
This thank you page needs to be translated, and also doesn't need a sign up or share. It's just static text.

I'm pretty sure this won't be the double opt in confirmation, but we can add some text to it saying an email has been sent to "your email" if and only if they clicked the singup button. Otherwise we should just say thank you.

**Comment by ScottDowne** [comment]
Also, I think it would be a nice touch to translate the thank-you in the url, but def not a p1.

**Comment by ScottDowne** [comment]
@edrushka @shaghdoosti this is going to need copy. I set up the thank you page with a header 1 and a header 2.

I also added a blob of text under the headers. The purpose of this is if they signed up, we can add a bit of text saying they should expect a sign up confirmation email. If they didn't sign up, we hide the text so they just see a thank you.

**Comment by edrushka** [comment]
cc @secretrobotron

**Comment by shaghdoosti** [comment]
This is what the Net Neutrality one looked like: 

http://mzl.la/1KkW2Ws

**Comment by secretrobotron** [comment]
Thank you page pull request: #5

**Comment by ScottDowne** [comment]
Done: https://github.com/mozilla/petitions.mozilla.org/pull/6

It is basically a copy from the donation de thank you page: https://sendto.mozilla.org/page/s/EOYFR2014-donor-de
