### ISSUE TITLE
Implement email sign-up

### ISSUE THREAD

**Issue by jbuck** [mozilla/petitions.mozilla.org#9]
After @adamlofting gets the [sign-up list implemented in ET](https://github.com/mozilla/petitions.mozilla.org/issues/2), I'll do the server-side implementation where we talk to ET.

**Comment by adamlofting** [comment]
Dev work can begin on this. The list is ready. The confirmation opt-in emails are not setup yet, but this doesn't block the dev.

Basket URL (connects to Exact Target Sandbox Account):
* Staging (connects to Exact Target Sandbox): `https://basket.allizom.org/...`
* Prod (connects to Exact Target Prod): `https://basket.mozilla.org/...`

Docs for subscriptions:
* http://basket.readthedocs.org/en/latest/newsletter_api.html#news-subscribe

Fields:
* newsletters: `mozilla-foundation`
* lang: `de`
* format: `html`
* optin: `N`
* source_url: `{{URL_of_form}}`
* trigger_welcome: `N`

No API key is needed as the list is double opt-in.

**Comment by jbuck** [comment]
Implementation in #38

**Comment by jbuck** [comment]
@adamlofting it looks like that newsletter hasn't been added to staging to production, but I tested with other newsletter codes and it worked fine.
